# Generated by Django 3.0.5 on 2020-06-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='static/pics'),
        ),
    ]
